[dosbox]
memsize=16
quit warning=false
[cpu]
cycles=max
core=normal
cputype=386
[dos]
xms=true
ems=false
umb=false
[mixer]
nosound=true
[sdl]
output=surface
[autoexec]
mount d "D:\Prog\simant_recon\build\workers\dos_fdata_selection_cause_v37a\compiler-scratch\pinned\496c3241308e53e8" -ro
mount e "D:\Prog\simant_recon\build\workers\dos_fdata_selection_cause_v37a\compiler-scratch\cecp7puva"
e:
set PATH=D:\BIN
set TMP=E:\
set TEMP=E:\
call RUN.BAT
exit
