#ifndef SIMANT_SDL3_WHOLE_AUDIO_STARTUP_H
#define SIMANT_SDL3_WHOLE_AUDIO_STARTUP_H
#include "whole_audio_provider.h"
int portable_sdl3_whole_audio_bind_source_services(PortableSdl3WholeAudio *audio);
void portable_sdl3_whole_audio_unbind_source_services(void);
#endif
