[dosbox]
memsize=16
quit warning=false
[cpu]
cycles=max
core=normal
cputype=386
[dos]
xms=true
ems=false
umb=false
[mixer]
nosound=true
[sdl]
output=surface
[autoexec]
mount c "D:\Prog\simant_recon\build\workers\dos_functional_fheap_owner_v36\api-only\rtlink400"
mount d "D:\Prog\simant_recon\build\workers\dos_functional_fheap_owner_v36\tool-scratch\pinned\b3924e2c4aa624d1" -ro
c:
set LIB=C:\;D:\
call RUN.BAT
exit
