[dosbox]
memsize=16
quit warning=false
[cpu]
cycles=max
core=normal
cputype=386
[dos]
xms=true
ems=false
umb=false
[mixer]
nosound=true
[sdl]
output=surface
[autoexec]
mount c "D:\Prog\simant_recon\build\workers\dos_tail_clear_v36\rtlink400\bss_two"
c:
call FULLRUN.BAT
exit
