[dosbox]
memsize=16
quit warning=false
[cpu]
cycles=max
core=normal
cputype=386
[dos]
xms=true
ems=false
umb=false
[mixer]
nosound=true
[sdl]
output=surface
[autoexec]
mount c "D:\Prog\simant_recon\build\workers\align\exp3"
mount d "C:\tools\rtlink-plus-6.10\installed" -ro
mount e "C:\tools\msc-6.00\BIN" -ro
c:
call RUN.BAT
exit
