#!/usr/bin/env python3
"""Extract and narrowly adapt original decoration bodies for native testing.

Allowed changes are limited to call signatures/qualifiers and the two raw
window-field expressions, which become typed fields. Statement order and all
remaining body text are copied from the original source files.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[5]
OUT = Path(__file__).resolve().parent / "extracted_bodies.inc"


def sha(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def function_span(path: Path, signature_prefix: str) -> tuple[str, int]:
    text = path.read_text(encoding="latin1")
    search = 0
    start = -1
    open_brace = -1
    while True:
        candidate = text.find(signature_prefix, search)
        if candidate < 0:
            break
        close_paren = text.find(")", candidate)
        probe = close_paren + 1
        while probe < len(text) and text[probe].isspace():
            probe += 1
        if close_paren >= 0 and probe < len(text) and text[probe] == "{":
            start, open_brace = candidate, probe
            break
        search = candidate + len(signature_prefix)
    if start < 0:
        raise RuntimeError(f"source signature missing: {path}:{signature_prefix}")
    if open_brace < 0:
        raise RuntimeError("function opening brace missing")
    depth = 0
    for pos in range(open_brace, len(text)):
        if text[pos] == "{":
            depth += 1
        elif text[pos] == "}":
            depth -= 1
            if depth == 0:
                return text[start:pos + 1], text[:start].count("\n") + 1
    raise RuntimeError("unclosed source function")


def replace_once(text: str, old: str, new: str, count: int = 1) -> str:
    found = text.count(old)
    if found != count:
        raise RuntimeError(f"conversion anchor count {found}, expected {count}: {old!r}")
    return text.replace(old, new)


def main() -> None:
    spec_path = Path(__file__).resolve().parent / "source-conversion.json"
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    if spec.get("schema") != "simant-window-source-body-conversion-v1":
        raise RuntimeError("unexpected source conversion schema")
    converted = []
    origins = []
    for function in spec["functions"]:
        source_path = ROOT / function["source"]
        body, line = function_span(source_path, function["signature_prefix"])
        original = body
        for replacement in function["replacements"]:
            body = replace_once(body, replacement["old"], replacement["new"],
                                replacement["count"])
        converted.append(body)
        origins.append({"name": function["name"], "source": source_path.relative_to(ROOT).as_posix(),
                        "line": line, "body_sha256": sha(original.encode("latin1"))})

    header = (
        "/* Generated by extract_bodies.py; no planner statements are synthesized.\n"
        + "".join(f" * {origin['name']} source {origin['source']}:{origin['line']}; body_sha256={origin['body_sha256']}.\n"
                   for origin in origins)
        + " * Typed field adaptations are enumerated in source-conversion.json. */\n"
    )
    OUT.write_text(header + "\n\n".join(converted) + "\n", encoding="latin1", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} sha256={sha(OUT.read_bytes())}")


if __name__ == "__main__":
    main()
