[dosbox]
memsize=16
quit warning=false
[cpu]
cycles=max
core=normal
cputype=386
[dos]
xms=true
ems=false
umb=false
[mixer]
nosound=true
[sdl]
output=surface
[autoexec]
mount c "D:\Prog\simant_recon\build\workers\dos_icon_minimum_v37\runtime\rtlink610\typed-overlay"
mount d "D:\Prog\simant_recon\build\workers\dos_icon_minimum_v37\cc\pinned\c95b3f9794e8fe01" -ro
c:
call RUN.BAT
exit
