"""Strict admission of the reviewed native History UI extension.

The complete Next9 parent is validated by the existing build path. The Next10
metadata and generated bytes are separately pinned; no inherited check is
relaxed to accommodate the S24 change.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PROFILE_SHA = "9659dfed65600f08be64edd32c52e5806835891f237d25201470e95d053adc6b"
PRODUCER_SHA = "81b7484e19e48a8e2c809aadb1308c7e0fa5da5b319f9c41aa3fcc87ff0edc6d"
PARENT_PATH = "portable/tests/recovered/evidence/next9-profile-regeneration-review-20261002/regenerated-provenance.json"
PARENT_SHA = "9821efeca4abdaf177f748c5179d9c7138618751641780b589baf7ac2efdf4ff"
RECEIPT_PATH = "portable/tests/history_event_lowering/comparison_report_closure_next10.json"
RECEIPT_SHA = "9c4329a240a1a695521a18d555001eca110e238e2294f14a48e3fbc16adb502a"
REVIEWED_PROFILE_PATH = "portable/tests/history_event_lowering/final-profile-provenance.json"
REVIEWED_PROFILE_SHA = "62b17c962c31cfa14e98bd3728cc4dffec80f004a3dda000958e2bf8b564111c"


def validate_next10(provenance: dict) -> tuple[dict, dict[str, str]]:
    """Return the unchanged parent and additional inputs for the build gate.

    Canonical JSON identity covers every ancestry, ABI, module, compile and
    object record, including the exact one-module lowering and snapshot API.
    Generated source hashes are still checked independently by the caller.
    """
    digest = hashlib.sha256(json.dumps(provenance, sort_keys=True,
        separators=(",", ":")).encode()).hexdigest()
    if digest != PROFILE_SHA:
        raise SystemExit("Unreviewed Next10 profile metadata")
    parent_file = ROOT / PARENT_PATH
    if hashlib.sha256(parent_file.read_bytes()).hexdigest() != PARENT_SHA:
        raise SystemExit("Next10 reviewed parent identity changed")
    parent = json.loads(parent_file.read_text(encoding="utf-8"))
    extension = provenance["versioned_profile_extension_next10"]
    if any(provenance.get(key) != value for key, value in parent.items()
           if key != "modules"):
        raise SystemExit("Next10 changed inherited profile metadata")
    pins = {
        "portable/tools/recover_source_next10.py": PRODUCER_SHA,
        PARENT_PATH: PARENT_SHA,
        RECEIPT_PATH: RECEIPT_SHA,
        REVIEWED_PROFILE_PATH: REVIEWED_PROFILE_SHA,
        extension["parent_regeneration_review"]["path"]:
            extension["parent_regeneration_review"]["sha256"],
    }
    modules = provenance["modules"]
    for row in modules:
        pins[row["generated"]] = row["generated_sha256"]
        command = row["compile"]["command"]
        if ((ROOT / command[command.index("-c") + 1]).resolve() !=
                (ROOT / row["generated"]).resolve() or
                row["compile"]["lowered_object_sha256"] !=
                row["compile"]["next10_object_sha256"] or
                row["compile"]["next10_recompiled"] is not True):
            raise SystemExit("Next10 source/compile/object identity disagrees")
    # Native TU includes and host linkage use copies in the selected output.
    # Pin them as actual inputs in addition to the unchanged parent's copies.
    output = Path(extension["native_lowering"]["generated_path"]).parent
    state = parent["recovered_state"]
    pins[(output / "recovered_state.h").as_posix()] = state["header_sha256"]
    pins[(output / "recovered_state.c").as_posix()] = state["source_sha256"]
    pins[(output / "recovered_native_adapters.c").as_posix()] = \
        parent["native_adapter_compile"]["source_sha256"]
    return parent, pins
