"""Independent root policies for typed screen and FAR state owners.

Literal controls encode fresh test-owned integer fields and fixups. They never
read candidates, original images, historical debt bytes or object capsules.
"""
from copy import deepcopy

POLICIES = {'source-owned:screen-clip-list': {'module': 'source-owned:screen-clip-list',
                                   'communals': [],
                                   'owners': ['_g_5A9C', '_g_574E', '_g_5AAC'],
                                   'required_cases': {'positive': 'PASS',
                                                      'far_data_owner': 'FAIL',
                                                      'wrong_fields': 'FAIL',
                                                      'wrong_order': 'FAIL',
                                                      'partial_sentinel': 'FAIL',
                                                      'wide_fields': 'FAIL',
                                                      'wrong_static_handle': 'FAIL',
                                                      'wrong_active_pointer': 'FAIL',
                                                      'wrong_segment_alias': 'FAIL',
                                                      'wrong_rect_alias': 'FAIL'},
                                   'control_outcomes': {'positive': 'PASS',
                                                        'far_data_owner': 'FAIL',
                                                        'wrong_fields': 'FAIL',
                                                        'wrong_order': 'FAIL',
                                                        'partial_sentinel': 'FAIL',
                                                        'wide_fields': 'FAIL',
                                                        'wrong_static_handle': 'FAIL',
                                                        'wrong_active_pointer': 'FAIL',
                                                        'wrong_segment_alias': 'FAIL',
                                                        'wrong_rect_alias': 'FAIL'},
                                   'linkers': ['rtlink400', 'rtlink610'],
                                   'aliases': {'positive': [{'alias': '_g_5AAE',
                                                             'target': '_g_5AAC',
                                                             'delta': 2},
                                                            {'alias': '_fd_55B3_5AA0',
                                                             'target': '_g_5A9C',
                                                             'delta': 4}],
                                               'far_data_owner': [{'alias': '_g_5AAE',
                                                                   'target': '_g_5AAC',
                                                                   'delta': 2},
                                                                  {'alias': '_fd_55B3_5AA0',
                                                                   'target': '_g_5A9C',
                                                                   'delta': 4}],
                                               'wrong_fields': [{'alias': '_g_5AAE',
                                                                 'target': '_g_5AAC',
                                                                 'delta': 2},
                                                                {'alias': '_fd_55B3_5AA0',
                                                                 'target': '_g_5A9C',
                                                                 'delta': 4}],
                                               'wrong_order': [{'alias': '_g_5AAE',
                                                                'target': '_g_5AAC',
                                                                'delta': 2},
                                                               {'alias': '_fd_55B3_5AA0',
                                                                'target': '_g_5A9C',
                                                                'delta': 4}],
                                               'partial_sentinel': [{'alias': '_g_5AAE',
                                                                     'target': '_g_5AAC',
                                                                     'delta': 2},
                                                                    {'alias': '_fd_55B3_5AA0',
                                                                     'target': '_g_5A9C',
                                                                     'delta': 4}],
                                               'wide_fields': [{'alias': '_g_5AAE',
                                                                'target': '_g_5AAC',
                                                                'delta': 2},
                                                               {'alias': '_fd_55B3_5AA0',
                                                                'target': '_g_5A9C',
                                                                'delta': 4}],
                                               'wrong_static_handle': [{'alias': '_g_5AAE',
                                                                        'target': '_g_5AAC',
                                                                        'delta': 2},
                                                                       {'alias': '_fd_55B3_5AA0',
                                                                        'target': '_g_5A9C',
                                                                        'delta': 4}],
                                               'wrong_active_pointer': [{'alias': '_g_5AAE',
                                                                         'target': '_g_5AAC',
                                                                         'delta': 2},
                                                                        {'alias': '_fd_55B3_5AA0',
                                                                         'target': '_g_5A9C',
                                                                         'delta': 4}],
                                               'wrong_segment_alias': [{'alias': '_g_5AAE',
                                                                        'target': '_g_5AAC',
                                                                        'delta': 4},
                                                                       {'alias': '_fd_55B3_5AA0',
                                                                        'target': '_g_5A9C',
                                                                        'delta': 4}],
                                               'wrong_rect_alias': [{'alias': '_g_5AAE',
                                                                     'target': '_g_5AAC',
                                                                     'delta': 2},
                                                                    {'alias': '_fd_55B3_5AA0',
                                                                     'target': '_g_5A9C',
                                                                     'delta': 6}]},
                                   'compiler_controls': {'positive': {'module_name': 'SCPOS.C',
                                                                      'owner_names': ['_g_5A9C'],
                                                                      'owner_communals': [],
                                                                      'owner_publics': [{'name': '_g_5A9C',
                                                                                         'segment': '_DATA',
                                                                                         'offset': 0}],
                                                                      'segment_lengths': {'SCPOS_TEXT': 0,
                                                                                          '_DATA': 16,
                                                                                          'CONST': 0,
                                                                                          '_BSS': 0},
                                                                      'initialized_data_hex': {'_DATA': '000000005d017f020080008000800080'},
                                                                      'linker_fixups': [],
                                                                      'full_communals': True,
                                                                      'all_communals': [],
                                                                      'full_publics': True,
                                                                      'all_publics': [{'name': '_g_5A9C',
                                                                                       'segment': '_DATA',
                                                                                       'offset': 0}],
                                                                      'full_segment_lengths': True,
                                                                      'all_segment_lengths': {'SCPOS_TEXT': 0,
                                                                                              '_DATA': 16,
                                                                                              'CONST': 0,
                                                                                              '_BSS': 0},
                                                                      'full_initialized_data': True,
                                                                      'all_initialized_data_hex': {'_DATA': '000000005d017f020080008000800080'},
                                                                      'no_external_fixups': True,
                                                                      'data_only': True},
                                                         'far_data_owner': {'module_name': 'SCFAR.C',
                                                                            'owner_names': ['_g_5A9C'],
                                                                            'owner_communals': [],
                                                                            'owner_publics': [{'name': '_g_5A9C',
                                                                                               'segment': 'SCFAR5_DATA',
                                                                                               'offset': 0}],
                                                                            'segment_lengths': {'SCFAR_TEXT': 0,
                                                                                                '_DATA': 0,
                                                                                                'CONST': 0,
                                                                                                '_BSS': 0,
                                                                                                'SCFAR5_DATA': 16},
                                                                            'initialized_data_hex': {'SCFAR5_DATA': '000000005d017f020080008000800080'},
                                                                            'linker_fixups': [],
                                                                            'full_communals': True,
                                                                            'all_communals': [],
                                                                            'full_publics': True,
                                                                            'all_publics': [{'name': '_g_5A9C',
                                                                                             'segment': 'SCFAR5_DATA',
                                                                                             'offset': 0}],
                                                                            'full_segment_lengths': True,
                                                                            'all_segment_lengths': {'SCFAR_TEXT': 0,
                                                                                                    '_DATA': 0,
                                                                                                    'CONST': 0,
                                                                                                    '_BSS': 0,
                                                                                                    'SCFAR5_DATA': 16},
                                                                            'full_initialized_data': True,
                                                                            'all_initialized_data_hex': {'SCFAR5_DATA': '000000005d017f020080008000800080'},
                                                                            'no_external_fixups': True,
                                                                            'data_only': True},
                                                         'wrong_fields': {'module_name': 'SCFLD.C',
                                                                          'owner_names': ['_g_5A9C'],
                                                                          'owner_communals': [],
                                                                          'owner_publics': [{'name': '_g_5A9C',
                                                                                             'segment': '_DATA',
                                                                                             'offset': 0}],
                                                                          'segment_lengths': {'SCFLD_TEXT': 0,
                                                                                              '_DATA': 16,
                                                                                              'CONST': 0,
                                                                                              '_BSS': 0},
                                                                          'initialized_data_hex': {'_DATA': '000000007f025d010080008000800080'},
                                                                          'linker_fixups': [],
                                                                          'full_communals': True,
                                                                          'all_communals': [],
                                                                          'full_publics': True,
                                                                          'all_publics': [{'name': '_g_5A9C',
                                                                                           'segment': '_DATA',
                                                                                           'offset': 0}],
                                                                          'full_segment_lengths': True,
                                                                          'all_segment_lengths': {'SCFLD_TEXT': 0,
                                                                                                  '_DATA': 16,
                                                                                                  'CONST': 0,
                                                                                                  '_BSS': 0},
                                                                          'full_initialized_data': True,
                                                                          'all_initialized_data_hex': {'_DATA': '000000007f025d010080008000800080'},
                                                                          'no_external_fixups': True,
                                                                          'data_only': True},
                                                         'wrong_order': {'module_name': 'SCORD.C',
                                                                         'owner_names': ['_g_5A9C'],
                                                                         'owner_communals': [],
                                                                         'owner_publics': [{'name': '_g_5A9C',
                                                                                            'segment': '_DATA',
                                                                                            'offset': 0}],
                                                                         'segment_lengths': {'SCORD_TEXT': 0,
                                                                                             '_DATA': 16,
                                                                                             'CONST': 0,
                                                                                             '_BSS': 0},
                                                                         'initialized_data_hex': {'_DATA': '0080008000800080000000005d017f02'},
                                                                         'linker_fixups': [],
                                                                         'full_communals': True,
                                                                         'all_communals': [],
                                                                         'full_publics': True,
                                                                         'all_publics': [{'name': '_g_5A9C',
                                                                                          'segment': '_DATA',
                                                                                          'offset': 0}],
                                                                         'full_segment_lengths': True,
                                                                         'all_segment_lengths': {'SCORD_TEXT': 0,
                                                                                                 '_DATA': 16,
                                                                                                 'CONST': 0,
                                                                                                 '_BSS': 0},
                                                                         'full_initialized_data': True,
                                                                         'all_initialized_data_hex': {'_DATA': '0080008000800080000000005d017f02'},
                                                                         'no_external_fixups': True,
                                                                         'data_only': True},
                                                         'partial_sentinel': {'module_name': 'SCSEN.C',
                                                                              'owner_names': ['_g_5A9C'],
                                                                              'owner_communals': [],
                                                                              'owner_publics': [{'name': '_g_5A9C',
                                                                                                 'segment': '_DATA',
                                                                                                 'offset': 0}],
                                                                              'segment_lengths': {'SCSEN_TEXT': 0,
                                                                                                  '_DATA': 16,
                                                                                                  'CONST': 0,
                                                                                                  '_BSS': 0},
                                                                              'initialized_data_hex': {'_DATA': '000000005d017f020000008000000000'},
                                                                              'linker_fixups': [],
                                                                              'full_communals': True,
                                                                              'all_communals': [],
                                                                              'full_publics': True,
                                                                              'all_publics': [{'name': '_g_5A9C',
                                                                                               'segment': '_DATA',
                                                                                               'offset': 0}],
                                                                              'full_segment_lengths': True,
                                                                              'all_segment_lengths': {'SCSEN_TEXT': 0,
                                                                                                      '_DATA': 16,
                                                                                                      'CONST': 0,
                                                                                                      '_BSS': 0},
                                                                              'full_initialized_data': True,
                                                                              'all_initialized_data_hex': {'_DATA': '000000005d017f020000008000000000'},
                                                                              'no_external_fixups': True,
                                                                              'data_only': True},
                                                         'wide_fields': {'module_name': 'SCWID.C',
                                                                         'owner_names': ['_g_5A9C'],
                                                                         'owner_communals': [],
                                                                         'owner_publics': [{'name': '_g_5A9C',
                                                                                            'segment': '_DATA',
                                                                                            'offset': 0}],
                                                                         'segment_lengths': {'SCWID_TEXT': 0,
                                                                                             '_DATA': 32,
                                                                                             'CONST': 0,
                                                                                             '_BSS': 0},
                                                                         'initialized_data_hex': {'_DATA': '00000000000000005d0100007f02000000800000008000000080000000800000'},
                                                                         'linker_fixups': [],
                                                                         'full_communals': True,
                                                                         'all_communals': [],
                                                                         'full_publics': True,
                                                                         'all_publics': [{'name': '_g_5A9C',
                                                                                          'segment': '_DATA',
                                                                                          'offset': 0}],
                                                                         'full_segment_lengths': True,
                                                                         'all_segment_lengths': {'SCWID_TEXT': 0,
                                                                                                 '_DATA': 32,
                                                                                                 'CONST': 0,
                                                                                                 '_BSS': 0},
                                                                         'full_initialized_data': True,
                                                                         'all_initialized_data_hex': {'_DATA': '00000000000000005d0100007f02000000800000008000000080000000800000'},
                                                                         'no_external_fixups': True,
                                                                         'data_only': True},
                                                         'static_handle_correct': {'module_name': 'HNDOK.C',
                                                                                   'owner_names': ['_g_574E'],
                                                                                   'owner_communals': [],
                                                                                   'owner_publics': [{'name': '_g_574E',
                                                                                                      'segment': '_DATA',
                                                                                                      'offset': 0}],
                                                                                   'segment_lengths': {'HNDOK_TEXT': 0,
                                                                                                       '_DATA': 4,
                                                                                                       'CONST': 0,
                                                                                                       '_BSS': 0},
                                                                                   'initialized_data_hex': {'_DATA': '00000000'},
                                                                                   'linker_fixups': [{'segment': '_DATA',
                                                                                                      'offset': 0,
                                                                                                      'width': 4,
                                                                                                      'loc': 'pointer32',
                                                                                                      'self_relative': False,
                                                                                                      'target_kind': 'external',
                                                                                                      'target': '_g_5A9C',
                                                                                                      'frame_kind': 'target',
                                                                                                      'frame': '_g_5A9C',
                                                                                                      'displacement': 0,
                                                                                                      'encoded_addend': '00000000'}],
                                                                                   'full_communals': True,
                                                                                   'all_communals': [],
                                                                                   'full_publics': True,
                                                                                   'all_publics': [{'name': '_g_574E',
                                                                                                    'segment': '_DATA',
                                                                                                    'offset': 0}],
                                                                                   'full_segment_lengths': True,
                                                                                   'all_segment_lengths': {'HNDOK_TEXT': 0,
                                                                                                           '_DATA': 4,
                                                                                                           'CONST': 0,
                                                                                                           '_BSS': 0},
                                                                                   'full_initialized_data': True,
                                                                                   'all_initialized_data_hex': {'_DATA': '00000000'},
                                                                                   'no_external_fixups': False,
                                                                                   'data_only': False},
                                                         'static_handle_wrong_target': {'module_name': 'HNDWR.C',
                                                                                        'owner_names': ['_g_574E'],
                                                                                        'owner_communals': [],
                                                                                        'owner_publics': [{'name': '_g_574E',
                                                                                                           'segment': '_DATA',
                                                                                                           'offset': 0}],
                                                                                        'segment_lengths': {'HNDWR_TEXT': 0,
                                                                                                            '_DATA': 4,
                                                                                                            'CONST': 0,
                                                                                                            '_BSS': 0},
                                                                                        'initialized_data_hex': {'_DATA': '08000000'},
                                                                                        'linker_fixups': [{'segment': '_DATA',
                                                                                                           'offset': 0,
                                                                                                           'width': 4,
                                                                                                           'loc': 'pointer32',
                                                                                                           'self_relative': False,
                                                                                                           'target_kind': 'external',
                                                                                                           'target': '_g_5A9C',
                                                                                                           'frame_kind': 'target',
                                                                                                           'frame': '_g_5A9C',
                                                                                                           'displacement': 0,
                                                                                                           'encoded_addend': '08000000'}],
                                                                                        'full_communals': True,
                                                                                        'all_communals': [],
                                                                                        'full_publics': True,
                                                                                        'all_publics': [{'name': '_g_574E',
                                                                                                         'segment': '_DATA',
                                                                                                         'offset': 0}],
                                                                                        'full_segment_lengths': True,
                                                                                        'all_segment_lengths': {'HNDWR_TEXT': 0,
                                                                                                                '_DATA': 4,
                                                                                                                'CONST': 0,
                                                                                                                '_BSS': 0},
                                                                                        'full_initialized_data': True,
                                                                                        'all_initialized_data_hex': {'_DATA': '08000000'},
                                                                                        'no_external_fixups': False,
                                                                                        'data_only': False},
                                                         'active_pointer_null': {'module_name': 'ACTOK.C',
                                                                                 'owner_names': ['_g_5AAC'],
                                                                                 'owner_communals': [],
                                                                                 'owner_publics': [{'name': '_g_5AAC',
                                                                                                    'segment': '_DATA',
                                                                                                    'offset': 0}],
                                                                                 'segment_lengths': {'ACTOK_TEXT': 0,
                                                                                                     '_DATA': 4,
                                                                                                     'CONST': 0,
                                                                                                     '_BSS': 0},
                                                                                 'initialized_data_hex': {'_DATA': '00000000'},
                                                                                 'linker_fixups': [],
                                                                                 'full_communals': True,
                                                                                 'all_communals': [],
                                                                                 'full_publics': True,
                                                                                 'all_publics': [{'name': '_g_5AAC',
                                                                                                  'segment': '_DATA',
                                                                                                  'offset': 0}],
                                                                                 'full_segment_lengths': True,
                                                                                 'all_segment_lengths': {'ACTOK_TEXT': 0,
                                                                                                         '_DATA': 4,
                                                                                                         'CONST': 0,
                                                                                                         '_BSS': 0},
                                                                                 'full_initialized_data': True,
                                                                                 'all_initialized_data_hex': {'_DATA': '00000000'},
                                                                                 'no_external_fixups': True,
                                                                                 'data_only': True},
                                                         'active_pointer_wrong_initialization': {'module_name': 'ACTWR.C',
                                                                                                 'owner_names': ['_g_5AAC'],
                                                                                                 'owner_communals': [],
                                                                                                 'owner_publics': [{'name': '_g_5AAC',
                                                                                                                    'segment': '_DATA',
                                                                                                                    'offset': 0}],
                                                                                                 'segment_lengths': {'ACTWR_TEXT': 0,
                                                                                                                     '_DATA': 4,
                                                                                                                     'CONST': 0,
                                                                                                                     '_BSS': 0},
                                                                                                 'initialized_data_hex': {'_DATA': '00000000'},
                                                                                                 'linker_fixups': [{'segment': '_DATA',
                                                                                                                    'offset': 0,
                                                                                                                    'width': 4,
                                                                                                                    'loc': 'pointer32',
                                                                                                                    'self_relative': False,
                                                                                                                    'target_kind': 'external',
                                                                                                                    'target': '_g_5A9C',
                                                                                                                    'frame_kind': 'target',
                                                                                                                    'frame': '_g_5A9C',
                                                                                                                    'displacement': 0,
                                                                                                                    'encoded_addend': '00000000'}],
                                                                                                 'full_communals': True,
                                                                                                 'all_communals': [],
                                                                                                 'full_publics': True,
                                                                                                 'all_publics': [{'name': '_g_5AAC',
                                                                                                                  'segment': '_DATA',
                                                                                                                  'offset': 0}],
                                                                                                 'full_segment_lengths': True,
                                                                                                 'all_segment_lengths': {'ACTWR_TEXT': 0,
                                                                                                                         '_DATA': 4,
                                                                                                                         'CONST': 0,
                                                                                                                         '_BSS': 0},
                                                                                                 'full_initialized_data': True,
                                                                                                 'all_initialized_data_hex': {'_DATA': '00000000'},
                                                                                                 'no_external_fixups': False,
                                                                                                 'data_only': False}},
                                   'save_rec_pointer_fixups': []},
 'source-owned:remaining-far-state-words': {'module': 'source-owned:remaining-far-state-words',
                                            'communals': [{'name': '_fd_50F6_04C0',
                                                           'kind': 'far',
                                                           'count': 2,
                                                           'element_size': 1,
                                                           'length': 2},
                                                          {'name': '_fd_50F6_0B20',
                                                           'kind': 'far',
                                                           'count': 2,
                                                           'element_size': 1,
                                                           'length': 2},
                                                          {'name': '_fd_50F6_0F38',
                                                           'kind': 'far',
                                                           'count': 2,
                                                           'element_size': 1,
                                                           'length': 2},
                                                          {'name': '_fd_50F6_0FB6',
                                                           'kind': 'far',
                                                           'count': 2,
                                                           'element_size': 1,
                                                           'length': 2},
                                                          {'name': '_fd_50F6_0FFA',
                                                           'kind': 'far',
                                                           'count': 2,
                                                           'element_size': 1,
                                                           'length': 2}],
                                            'owners': ['_fd_50F6_04C0',
                                                       '_fd_50F6_0B20',
                                                       '_fd_50F6_0F38',
                                                       '_fd_50F6_0FB6',
                                                       '_fd_50F6_0FFA'],
                                            'required_cases': {'typed_raw_startup0': 'PASS',
                                                               'typed_raw_boundary_guard': 'PASS',
                                                               'unsigned_signedness_contrast': 'FAIL',
                                                               'initialized_owner_startup_contrast': 'FAIL'},
                                            'control_outcomes': {'typed_raw_startup0': 'PASS',
                                                                 'typed_raw_boundary_guard': 'PASS',
                                                                 'unsigned_signedness_contrast': 'FAIL',
                                                                 'initialized_owner_startup_contrast': 'FAIL'},
                                            'linkers': ['rtlink400', 'rtlink610'],
                                            'aliases': {'typed_raw_startup0': [],
                                                        'typed_raw_boundary_guard': [],
                                                        'unsigned_signedness_contrast': [],
                                                        'initialized_owner_startup_contrast': []},
                                            'save_rec_pointer_fixups': [],
                                            'compiler_controls': {'OWNV35': {'module_name': 'OWNV35.C',
                                                                             'owner_names': ['_fd_50F6_04C0',
                                                                                             '_fd_50F6_0B20',
                                                                                             '_fd_50F6_0F38',
                                                                                             '_fd_50F6_0FB6',
                                                                                             '_fd_50F6_0FFA'],
                                                                             'owner_communals': [{'name': '_fd_50F6_04C0',
                                                                                                  'kind': 'far',
                                                                                                  'count': 2,
                                                                                                  'element_size': 1,
                                                                                                  'length': 2},
                                                                                                 {'name': '_fd_50F6_0B20',
                                                                                                  'kind': 'far',
                                                                                                  'count': 2,
                                                                                                  'element_size': 1,
                                                                                                  'length': 2},
                                                                                                 {'name': '_fd_50F6_0F38',
                                                                                                  'kind': 'far',
                                                                                                  'count': 2,
                                                                                                  'element_size': 1,
                                                                                                  'length': 2},
                                                                                                 {'name': '_fd_50F6_0FB6',
                                                                                                  'kind': 'far',
                                                                                                  'count': 2,
                                                                                                  'element_size': 1,
                                                                                                  'length': 2},
                                                                                                 {'name': '_fd_50F6_0FFA',
                                                                                                  'kind': 'far',
                                                                                                  'count': 2,
                                                                                                  'element_size': 1,
                                                                                                  'length': 2}],
                                                                             'owner_publics': [],
                                                                             'segment_lengths': {'OWNV35_TEXT': 0,
                                                                                                 '_DATA': 0,
                                                                                                 'CONST': 0,
                                                                                                 '_BSS': 0},
                                                                             'initialized_data_hex': {},
                                                                             'linker_fixups': [],
                                                                             'full_communals': True,
                                                                             'all_communals': [{'name': '_fd_50F6_04C0',
                                                                                                'kind': 'far',
                                                                                                'count': 2,
                                                                                                'element_size': 1,
                                                                                                'length': 2},
                                                                                               {'name': '_fd_50F6_0B20',
                                                                                                'kind': 'far',
                                                                                                'count': 2,
                                                                                                'element_size': 1,
                                                                                                'length': 2},
                                                                                               {'name': '_fd_50F6_0F38',
                                                                                                'kind': 'far',
                                                                                                'count': 2,
                                                                                                'element_size': 1,
                                                                                                'length': 2},
                                                                                               {'name': '_fd_50F6_0FB6',
                                                                                                'kind': 'far',
                                                                                                'count': 2,
                                                                                                'element_size': 1,
                                                                                                'length': 2},
                                                                                               {'name': '_fd_50F6_0FFA',
                                                                                                'kind': 'far',
                                                                                                'count': 2,
                                                                                                'element_size': 1,
                                                                                                'length': 2}],
                                                                             'full_publics': True,
                                                                             'all_publics': [],
                                                                             'full_segment_lengths': True,
                                                                             'all_segment_lengths': {'OWNV35_TEXT': 0,
                                                                                                     '_DATA': 0,
                                                                                                     'CONST': 0,
                                                                                                     '_BSS': 0},
                                                                             'full_initialized_data': True,
                                                                             'all_initialized_data_hex': {},
                                                                             'data_only': True,
                                                                             'no_external_fixups': True},
                                                                  'WIDV35': {'module_name': 'WIDV35.C',
                                                                             'owner_names': ['_fd_50F6_04C0',
                                                                                             '_fd_50F6_0B20',
                                                                                             '_fd_50F6_0F38',
                                                                                             '_fd_50F6_0FB6',
                                                                                             '_fd_50F6_0FFA'],
                                                                             'owner_communals': [{'name': '_fd_50F6_04C0',
                                                                                                  'kind': 'far',
                                                                                                  'count': 4,
                                                                                                  'element_size': 1,
                                                                                                  'length': 4},
                                                                                                 {'name': '_fd_50F6_0B20',
                                                                                                  'kind': 'far',
                                                                                                  'count': 2,
                                                                                                  'element_size': 1,
                                                                                                  'length': 2},
                                                                                                 {'name': '_fd_50F6_0F38',
                                                                                                  'kind': 'far',
                                                                                                  'count': 2,
                                                                                                  'element_size': 1,
                                                                                                  'length': 2},
                                                                                                 {'name': '_fd_50F6_0FB6',
                                                                                                  'kind': 'far',
                                                                                                  'count': 2,
                                                                                                  'element_size': 1,
                                                                                                  'length': 2},
                                                                                                 {'name': '_fd_50F6_0FFA',
                                                                                                  'kind': 'far',
                                                                                                  'count': 2,
                                                                                                  'element_size': 1,
                                                                                                  'length': 2}],
                                                                             'owner_publics': [],
                                                                             'segment_lengths': {'WIDV35_TEXT': 0,
                                                                                                 '_DATA': 0,
                                                                                                 'CONST': 0,
                                                                                                 '_BSS': 0},
                                                                             'initialized_data_hex': {},
                                                                             'linker_fixups': [],
                                                                             'full_communals': True,
                                                                             'all_communals': [{'name': '_fd_50F6_04C0',
                                                                                                'kind': 'far',
                                                                                                'count': 4,
                                                                                                'element_size': 1,
                                                                                                'length': 4},
                                                                                               {'name': '_fd_50F6_0B20',
                                                                                                'kind': 'far',
                                                                                                'count': 2,
                                                                                                'element_size': 1,
                                                                                                'length': 2},
                                                                                               {'name': '_fd_50F6_0F38',
                                                                                                'kind': 'far',
                                                                                                'count': 2,
                                                                                                'element_size': 1,
                                                                                                'length': 2},
                                                                                               {'name': '_fd_50F6_0FB6',
                                                                                                'kind': 'far',
                                                                                                'count': 2,
                                                                                                'element_size': 1,
                                                                                                'length': 2},
                                                                                               {'name': '_fd_50F6_0FFA',
                                                                                                'kind': 'far',
                                                                                                'count': 2,
                                                                                                'element_size': 1,
                                                                                                'length': 2}],
                                                                             'full_publics': True,
                                                                             'all_publics': [],
                                                                             'full_segment_lengths': True,
                                                                             'all_segment_lengths': {'WIDV35_TEXT': 0,
                                                                                                     '_DATA': 0,
                                                                                                     'CONST': 0,
                                                                                                     '_BSS': 0},
                                                                             'full_initialized_data': True,
                                                                             'all_initialized_data_hex': {},
                                                                             'data_only': True,
                                                                             'no_external_fixups': True},
                                                                  'SIGV35': {'module_name': 'SIGV35.C',
                                                                             'owner_names': ['_fd_50F6_04C0',
                                                                                             '_fd_50F6_0B20',
                                                                                             '_fd_50F6_0F38',
                                                                                             '_fd_50F6_0FB6',
                                                                                             '_fd_50F6_0FFA'],
                                                                             'owner_communals': [{'name': '_fd_50F6_04C0',
                                                                                                  'kind': 'far',
                                                                                                  'count': 2,
                                                                                                  'element_size': 1,
                                                                                                  'length': 2},
                                                                                                 {'name': '_fd_50F6_0B20',
                                                                                                  'kind': 'far',
                                                                                                  'count': 2,
                                                                                                  'element_size': 1,
                                                                                                  'length': 2},
                                                                                                 {'name': '_fd_50F6_0F38',
                                                                                                  'kind': 'far',
                                                                                                  'count': 2,
                                                                                                  'element_size': 1,
                                                                                                  'length': 2},
                                                                                                 {'name': '_fd_50F6_0FB6',
                                                                                                  'kind': 'far',
                                                                                                  'count': 2,
                                                                                                  'element_size': 1,
                                                                                                  'length': 2},
                                                                                                 {'name': '_fd_50F6_0FFA',
                                                                                                  'kind': 'far',
                                                                                                  'count': 2,
                                                                                                  'element_size': 1,
                                                                                                  'length': 2}],
                                                                             'owner_publics': [],
                                                                             'segment_lengths': {'SIGV35_TEXT': 0,
                                                                                                 '_DATA': 0,
                                                                                                 'CONST': 0,
                                                                                                 '_BSS': 0},
                                                                             'initialized_data_hex': {},
                                                                             'linker_fixups': [],
                                                                             'full_communals': True,
                                                                             'all_communals': [{'name': '_fd_50F6_04C0',
                                                                                                'kind': 'far',
                                                                                                'count': 2,
                                                                                                'element_size': 1,
                                                                                                'length': 2},
                                                                                               {'name': '_fd_50F6_0B20',
                                                                                                'kind': 'far',
                                                                                                'count': 2,
                                                                                                'element_size': 1,
                                                                                                'length': 2},
                                                                                               {'name': '_fd_50F6_0F38',
                                                                                                'kind': 'far',
                                                                                                'count': 2,
                                                                                                'element_size': 1,
                                                                                                'length': 2},
                                                                                               {'name': '_fd_50F6_0FB6',
                                                                                                'kind': 'far',
                                                                                                'count': 2,
                                                                                                'element_size': 1,
                                                                                                'length': 2},
                                                                                               {'name': '_fd_50F6_0FFA',
                                                                                                'kind': 'far',
                                                                                                'count': 2,
                                                                                                'element_size': 1,
                                                                                                'length': 2}],
                                                                             'full_publics': True,
                                                                             'all_publics': [],
                                                                             'full_segment_lengths': True,
                                                                             'all_segment_lengths': {'SIGV35_TEXT': 0,
                                                                                                     '_DATA': 0,
                                                                                                     'CONST': 0,
                                                                                                     '_BSS': 0},
                                                                             'full_initialized_data': True,
                                                                             'all_initialized_data_hex': {},
                                                                             'data_only': True,
                                                                             'no_external_fixups': True},
                                                                  'INITV35': {'module_name': 'INITV35.C',
                                                                              'owner_names': ['_fd_50F6_04C0',
                                                                                              '_fd_50F6_0B20',
                                                                                              '_fd_50F6_0F38',
                                                                                              '_fd_50F6_0FB6',
                                                                                              '_fd_50F6_0FFA'],
                                                                              'owner_communals': [{'name': '_fd_50F6_0B20',
                                                                                                   'kind': 'far',
                                                                                                   'count': 2,
                                                                                                   'element_size': 1,
                                                                                                   'length': 2},
                                                                                                  {'name': '_fd_50F6_0F38',
                                                                                                   'kind': 'far',
                                                                                                   'count': 2,
                                                                                                   'element_size': 1,
                                                                                                   'length': 2},
                                                                                                  {'name': '_fd_50F6_0FB6',
                                                                                                   'kind': 'far',
                                                                                                   'count': 2,
                                                                                                   'element_size': 1,
                                                                                                   'length': 2},
                                                                                                  {'name': '_fd_50F6_0FFA',
                                                                                                   'kind': 'far',
                                                                                                   'count': 2,
                                                                                                   'element_size': 1,
                                                                                                   'length': 2}],
                                                                              'owner_publics': [{'name': '_fd_50F6_04C0',
                                                                                                 'segment': 'INITV355_DATA',
                                                                                                 'offset': 0}],
                                                                              'segment_lengths': {'INITV35_TEXT': 0,
                                                                                                  '_DATA': 0,
                                                                                                  'CONST': 0,
                                                                                                  '_BSS': 0,
                                                                                                  'INITV355_DATA': 2},
                                                                              'initialized_data_hex': {'INITV355_DATA': '0100'},
                                                                              'linker_fixups': [],
                                                                              'full_communals': True,
                                                                              'all_communals': [{'name': '_fd_50F6_0B20',
                                                                                                 'kind': 'far',
                                                                                                 'count': 2,
                                                                                                 'element_size': 1,
                                                                                                 'length': 2},
                                                                                                {'name': '_fd_50F6_0F38',
                                                                                                 'kind': 'far',
                                                                                                 'count': 2,
                                                                                                 'element_size': 1,
                                                                                                 'length': 2},
                                                                                                {'name': '_fd_50F6_0FB6',
                                                                                                 'kind': 'far',
                                                                                                 'count': 2,
                                                                                                 'element_size': 1,
                                                                                                 'length': 2},
                                                                                                {'name': '_fd_50F6_0FFA',
                                                                                                 'kind': 'far',
                                                                                                 'count': 2,
                                                                                                 'element_size': 1,
                                                                                                 'length': 2}],
                                                                              'full_publics': True,
                                                                              'all_publics': [{'name': '_fd_50F6_04C0',
                                                                                               'segment': 'INITV355_DATA',
                                                                                               'offset': 0}],
                                                                              'full_segment_lengths': True,
                                                                              'all_segment_lengths': {'INITV35_TEXT': 0,
                                                                                                      '_DATA': 0,
                                                                                                      'CONST': 0,
                                                                                                      '_BSS': 0,
                                                                                                      'INITV355_DATA': 2},
                                                                              'full_initialized_data': True,
                                                                              'all_initialized_data_hex': {'INITV355_DATA': '0100'},
                                                                              'data_only': True,
                                                                              'no_external_fixups': True}}}}

CONTRACTS = {module: (
    'screen_clip_list_contract' if module == 'source-owned:screen-clip-list'
    else 'remaining_far_state_words_contract', row['required_cases'])
    for module, row in POLICIES.items()}

def policy(module):
    return deepcopy(POLICIES[module])
