"""Strict contribution matcher: bind a candidate OMF object symbolically and compare.

A *contribution* is an extent of an oracle unit (``root`` or ``Snn``) that one
candidate object segment claims, e.g. one function or a whole module segment.
Acceptance requires, with no masking:

  * the candidate segment extent (public offset .. next public / segment end,
    excluding only an MSC word-alignment ``90`` pad at the very end) has exactly
    the target length;
  * every FIXUPP inside the extent binds to a registered symbol, the
    contribution's own segment, or a declared data placement;
  * the bound bytes equal the original bytes;
  * the relocations generated by those fixups equal, in order, the oracle's
    relocation entries inside the extent;
  * every private data placement (``_DATA``/``CONST`` of the same object) that
    the extent references is itself byte-equal, after binding, to the oracle.

Symbols come from layout/symbols.json (names -> addresses grounded by original
anchors).  Nothing here reads original bytes to *produce* candidate bytes: the
oracle is only compared against.
"""
from __future__ import annotations

import json
import struct
import sys
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import exe as exemod  # noqa: E402
from omf import OmfReader  # noqa: E402

ROOT = exemod.ROOT
SYMBOLS = ROOT / "layout" / "symbols.json"
DGROUP_SEG = 0x55B3
MANAGER_SEG = exemod.MANAGER_SEG


@lru_cache(maxsize=1)
def symbols() -> dict:
    """{c_name: {kind: code|data, unit, seg, off}}; OBJ names add a leading underscore."""
    if not SYMBOLS.exists():
        return {}
    raw = json.loads(SYMBOLS.read_text())
    out = {}
    for kind in ("code", "data"):
        for name, s in raw.get(kind, {}).items():
            out["_" + name] = {"kind": kind, **s}
    for name, s in raw.get("runtime", {}).items():
        out.setdefault(name, {"kind": "code", **s})
    return out


def obj_name_lookup(name: str) -> dict | None:
    """Resolve an OBJ-level name (C names carry a leading underscore; MSC 6
    _fastcall names carry a leading '@')."""
    if name.startswith("@"):
        name = "_" + name[1:]
    return symbols().get(name)


def public_in(obj, cname: str):
    """(decorated name, public record) of C function ``cname`` in ``obj``."""
    for p in obj.publics + getattr(obj, "local_publics", []):
        if p["name"] in ("_" + cname, "@" + cname):
            return p["name"], p
    return None, None


@dataclass
class Target:
    unit: str
    seg: int          # frame (load-relative paragraph)
    off: int          # offset of the extent start within the frame
    size: int

    @property
    def linear(self) -> int:
        return self.seg * 16 + self.off


@dataclass
class MatchResult:
    exact: bool
    reasons: list = field(default_factory=list)
    candidate: bytes = b""
    original: bytes = b""
    first_diff: int | None = None
    relocs_expected: list = field(default_factory=list)
    relocs_candidate: list = field(default_factory=list)
    fixups: list = field(default_factory=list)
    data_checks: list = field(default_factory=list)
    unbound: list = field(default_factory=list)
    reloc_order: str = "EXACT"      # EXACT | GROUPED (object order exact per target; group order = link)

    def summary(self) -> str:
        if self.exact:
            return (f"EXACT {len(self.candidate)} bytes, {len(self.fixups)} fixups, "
                    f"{len(self.relocs_expected)} relocations (order {self.reloc_order})")
        return "MISMATCH: " + "; ".join(self.reasons)


def vector_for(unit: str, seg: int, off: int):
    x = exemod.load()
    sec = 0xFFFF if unit == "root" else int(unit[1:])
    for v in x.vectors:
        if v.section == sec and v.target_seg == seg and v.target_off == off:
            return v
    return None


class Binder:
    def __init__(self, target: Target, obj, segment: str, public: str,
                 placements: dict | None = None):
        self.t = target
        self.obj = obj
        self.segment = segment
        self.public = public
        self.placements = placements or {}   # segment name -> {"seg": frame, "off": offset}
        self.x = exemod.load()

    def own_segment_delta(self, pub_off: int) -> int:
        return self.t.off - pub_off

    def resolve(self, f: dict, pub_off: int):
        """Return (kind, unit, seg, off) for the fixup target, or raise KeyError."""
        tk, tname = f["target_kind"], f["target"]
        if tk == "external":
            s = obj_name_lookup(tname)
            if s is None:
                raise KeyError(f"unregistered external {tname}")
            if s["kind"] == "data":
                return "data", s.get("unit"), s["seg"], s["off"]
            return "code", s["unit"], s["seg"], s["off"]
        if tk == "segment":
            if tname == self.segment:
                return "own", self.t.unit, self.t.seg, None
            if tname in self.placements:
                p = self.placements[tname]
                return "placed", None, p["seg"], p["off"]
            raise KeyError(f"no placement for segment {tname}")
        if tk == "group" and tname == "DGROUP":
            return "group", None, DGROUP_SEG, 0
        raise KeyError(f"unsupported target {tk}:{tname}")

    def bind(self) -> MatchResult:
        t = self.t
        res = MatchResult(False)
        obj = self.obj
        if self.segment not in obj.segments:
            res.reasons.append(f"candidate has no segment {self.segment}")
            return res
        body = bytearray(obj.segments[self.segment])
        pubs = sorted((p for p in obj.publics + getattr(obj, "local_publics", [])
                       if p["segment"] == self.segment), key=lambda p: p["offset"])
        pub = next((p for p in pubs if p["name"] == self.public), None)
        if pub is None and self.public.startswith("_"):
            pub = next((p for p in pubs if p["name"] == "@" + self.public[1:]), None)
        if pub is None:
            res.reasons.append(f"candidate lacks public {self.public}")
            return res
        pub_off = pub["offset"]
        nxt = next((p["offset"] for p in pubs if p["offset"] > pub_off), None)
        seglen = len(body)
        if nxt is None:
            end = seglen
            if seglen - pub_off == t.size + 1 and body[-1] == 0x90 and seglen % 2 == 0:
                end = seglen - 1   # MSC word-alignment pad at segment end
        else:
            end = nxt
        if end - pub_off != t.size:
            res.reasons.append(f"length {end - pub_off} != target {t.size}")
        size = min(end - pub_off, t.size)
        payload = bytearray(body[pub_off:pub_off + size])
        _, data = self.x.unit_bytes(t.unit)
        base, _ = self.x.unit_bytes(t.unit)
        orig = data[t.linear - base:t.linear - base + t.size]
        res.original = bytes(orig)
        cand_relocs = []
        reloc_key = {}
        delta = self.own_segment_delta(pub_off)
        for f in obj.linker_fixups:
            if f["segment"] != self.segment:
                continue
            o = f["offset"]
            if not (pub_off <= o < pub_off + size):
                if o < pub_off + size and o + f["width"] > pub_off:
                    res.reasons.append(f"fixup straddles extent at {o:#x}")
                continue
            rel = o - pub_off
            if o + f["width"] > pub_off + size:
                res.reasons.append(f"fixup at +{rel:#x} crosses the extent end")
                continue
            site_off = t.off + rel                     # offset within target frame
            addend = int.from_bytes(bytes.fromhex(f["encoded_addend"]), "little")
            disp = f.get("displacement") or 0
            try:
                kind, unit, seg, off = self.resolve(f, pub_off)
            except KeyError as e:
                res.unbound.append(str(e))
                continue
            loc = f["loc"]
            rec = {"at": rel, "loc": loc, "target": f["target"], "kind": kind}
            if kind == "own":
                seg = t.seg
                off = None
            # far code targets in another overlay go through the RTLink vector
            if kind == "code" and unit != t.unit and unit != "root":
                v = vector_for(unit, seg, off)
                if v is None:
                    res.unbound.append(f"no RTLink vector for {unit}:{seg:04X}:{off:04X}")
                    continue
                seg, off = MANAGER_SEG, v.offset
                rec["via_vector"] = f"{v.offset:04X}"
            if loc in ("offset16", "pointer32", "loader-offset16"):
                if kind == "own":
                    tgt_off = (addend + disp + delta) & 0xFFFF
                elif kind == "group":
                    tgt_off = (addend + disp) & 0xFFFF
                elif kind == "placed":
                    if f["frame_kind"] == "group" and f["frame"] == "DGROUP":
                        tgt_off = (seg * 16 + off - DGROUP_SEG * 16 + addend + disp) & 0xFFFF
                    else:
                        tgt_off = (off + addend + disp) & 0xFFFF
                else:
                    if f["frame_kind"] == "group" and f["frame"] == "DGROUP":
                        tgt_off = (seg * 16 + off - DGROUP_SEG * 16 + addend + disp) & 0xFFFF
                    else:
                        tgt_off = (off + addend + disp) & 0xFFFF
                if f["self_relative"]:
                    if kind in ("code", "own") and seg != t.seg:
                        res.unbound.append(f"self-relative fixup to other frame {f['target']}")
                        continue
                    val = (tgt_off - (site_off + 2)) & 0xFFFF
                    struct.pack_into("<H", payload, rel, val)
                else:
                    struct.pack_into("<H", payload, rel, tgt_off)
                if loc == "pointer32":
                    frame = seg if kind != "group" else DGROUP_SEG
                    struct.pack_into("<H", payload, rel + 2, frame)
                    cand_relocs.append(t.linear + rel + 2)
                    reloc_key[t.linear + rel + 2] = f"{f['target_kind']}:{f['target']}"
            elif loc == "base16":
                frame = seg if kind != "group" else DGROUP_SEG
                struct.pack_into("<H", payload, rel, frame)
                cand_relocs.append(t.linear + rel)
                reloc_key[t.linear + rel] = f"{f['target_kind']}:{f['target']}"
            else:
                res.unbound.append(f"unsupported fixup location {loc}")
                continue
            res.fixups.append(rec)
        # oracle relocations inside the extent, in table order
        exp = [s * 16 + o for s, o in self.x.unit_relocs(t.unit) if t.linear <= s * 16 + o < t.linear + t.size]
        res.relocs_expected = exp
        res.relocs_candidate = cand_relocs
        res.candidate = bytes(payload)
        if res.unbound:
            res.reasons.append(f"{len(res.unbound)} unbound fixups: " + ", ".join(sorted(set(res.unbound))[:4]))
        if res.candidate != res.original:
            n = min(len(res.candidate), len(res.original))
            res.first_diff = next((i for i in range(n) if res.candidate[i] != res.original[i]), n)
            ndiff = sum(1 for i in range(n) if res.candidate[i] != res.original[i])
            res.reasons.append(f"bytes differ (first at +{res.first_diff:#x}, {ndiff} differing)")
        if sorted(exp) != sorted(cand_relocs):
            res.reasons.append(f"relocation set differs ({len(cand_relocs)} vs {len(exp)})")
        elif exp != cand_relocs:
            # RTLink groups a module's relocations by target symbol in a program-wide symbol
            # order (a linker property, docs/exe-format.md) and keeps the object's FIXUPP order
            # inside each group (an object property).  The object part is checked here; the
            # group order is left to the historical link.
            groups = sorted(set(reloc_key.values()))
            within_ok = all([a for a in exp if reloc_key.get(a) == g] == [a for a in cand_relocs if reloc_key.get(a) == g]
                            for g in groups)
            if within_ok:
                res.reloc_order = "GROUPED"
            else:
                res.reloc_order = "WITHIN_GROUP_MISMATCH"
                res.reasons.append("relocation order inside a target group differs from the object's FIXUPP order")
        res.exact = not res.reasons
        return res


def match_object(obj_bytes: bytes, target: Target, segment: str, public: str,
                 placements: dict | None = None) -> MatchResult:
    obj = OmfReader(communals=True).read(obj_bytes)
    return Binder(target, obj, segment, public, placements).bind()
