from pathlib import Path
import json,sys
sys.path.insert(0,'tools')
import modctx,variants
ctx=modctx.resolve(func='o17_384C_0039');p=Path('build/workers/continue_next/s17-home-ranking/021_reset-int-before_fixup.c');base=p.read_text().replace('extern void far f_1FD2_0663(int a);','extern int far f_1FD2_0663(int draw);').replace('reset','draw')
base=base.replace('int far o17_384C_0039(int id)','/* LIFE-2: draw is a real later call argument. Initializing it before the\n * pointer-fixup loops reproduces the frame and spill homes. Its spelling and\n * original width are unknown; int, unsigned and unsigned char controls match. */\nint far o17_384C_0039(int id)')
neg=base.replace('    int draw;\n','').replace('    draw = 0;\n','').replace('f_1FD2_0663(draw);','f_1FD2_0663(0);')
late=base.replace('    draw = 0;\n','').replace('    f_1FD2_0663(draw);','    draw = 0;\n    f_1FD2_0663(draw);')
out=Path('build/workers/continue_next/s17-reviewed');out.mkdir(parents=True,exist_ok=True)
rows=variants.run(ctx,[('early-draw',base,''),('late-draw',late,''),('literal-draw',neg,''),('early-unsigned',base.replace('    int draw;','    unsigned draw;'),''),('early-byte',base.replace('    int draw;','    unsigned char draw;'),'')],extra_funcs=['o17_384C_0039'],claims_only=True,jobs=6,out_dir=out)
(out/'results.json').write_text(json.dumps({'function':'o17_384C_0039','profile':ctx.profile,'flags':ctx.flags,'variants':rows},indent=1))
for row in rows:print(row['name'],row['result']['claims']['o17_384C_0039'],flush=True)
spec={'id':'LIFE-2','question':'In the preserved S17 whole-module context, does a used zero draw argument initialized before pointer-fixup loops retain the extra frame word and reproduce the original spill homes?', 'notes':['Context-specific. The draw local is used by the existing menu setup call; no folded artificial read or padding declaration is added.','int, unsigned and unsigned-char draw types match; original type, spelling and exact source placement are not recovered. The accepted target is layout-inferred.','Early draw is exact across five functions, CONST and the complete 443-byte module. Moving the same assignment just before its call, or using literal zero, leaves a 16-byte frame and twelve operand differences. Whole-module binding evidence is in work/takeover/menu-loader/.'], 'variants':{'early_draw':base,'late_draw':late,'literal_draw':neg},'profiles':[{'profile':ctx.profile,'flags':ctx.flags}], 'expect':{'early_draw@0':'push bp; mov bp, sp; sub sp, 0x12; push di; push si; mov di, word ptr [bp + 6]','late_draw@0':'push bp; mov bp, sp; sub sp, 0x10; push di; push si; mov di, word ptr [bp + 6]','literal_draw@0':'push bp; mov bp, sp; sub sp, 0x10; push di; push si; mov di, word ptr [bp + 6]'}, 'expect_segments':{k+'@0':{'UNIT_TEXT':{'length':443},'CONST':{'length':16}} for k in ['early_draw','late_draw','literal_draw']}}
Path('evidence/codegen/LIFE-2-used-menu-draw-lifetime.json').write_text(json.dumps(spec,indent=1)+'\n',encoding='utf-8',newline='\n')
